# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

$info_plist_path = "./ShowsTracker/SupportingFiles/Info.plist"
$bundle_version_key = "CFBundleVersion"
$bundle_short_version = "CFBundleShortVersionString"

desc "Push a new build to TestFlight"
lane :release do
  build_app(scheme: "ShowsTracker")
  upload_to_testflight
  increment_build_number(true)
  setTag
end

def increment_build_number(push)
  current_build_number = get_info_plist_value(path: $info_plist_path, key: $bundle_version_key)
  build_number = (current_build_number.to_i + 1).to_s
  set_info_plist_value(path: $info_plist_path, key: $bundle_version_key, value: build_number)

  if push
    sh("git add .#{$info_plist_path}")
    sh("git commit -m \"Increment build number to #{build_number}\"")
    sh("git push")
  end
end

def setTag
  current_build_number = get_info_plist_value(path: $info_plist_path, key: $bundle_version_key)
  current_version = get_info_plist_value(path: $info_plist_path, key: $bundle_short_version)
  sh("git tag \"#{current_version}/#{current_build_number}\"")
  sh("git push --tags")
end